### ISSUE TITLE
.litcoffee files support

### ISSUE THREAD

**Issue by giano** [Ziink/atom-nav-panel#6]
Would be nice to activate nav-panel for literal coffeescript as well. Btw: seems not to parse and display on .coffee files ATM.

Great plugin!

**Comment by Ziink** [comment]
Should now recognize .litcoffee files as CoffeeScript. It should already have worked fine on .coffee files.  Does it not work for you on any .coffee files?

**Comment by giano** [comment]
Thank you for the fast fix. But sorry to say it's not popping on coffee files, nor litcoffee. Maybe a conflict with some other package. Any way to send you a log or help you in any way?

**Comment by giano** [comment]
Ignore me, an Atom restart fixed everything. Thank you., Great package!

**Comment by giano** [comment]
BTW: litcoffee parsing is working too. :)
